services:
  api:
    build:
      context: ./api
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./api/.env
    volumes:
      - ./api/logs:/app/logs
    depends_on:
      - postgres
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
volumes:
  db:
